- hosts: apache
  sudo: yes
  tasks:
    - name: install aoache2
      apt: name=apache2 update_cache=yes state=latest
    - name: enable_mod_rewrite
      apache2_module: name=rewrite state=present
    - name: copy index
      template: src=index.html.j2 dest=/var/www/html/index.html
    - name: create new doc root
      file: path=/data/html state=directory mode=0755 group=root owner=root
    - name: copy index
      template: src=index.html.j2 dest=/data/html/index.html
    - name: allow doc root
      replace: path=/etc/apache2/apache2.conf regexp='<Directory \/var\/www\/>' replace='<Directory /data/>' backup=yes
    - name: replace doc root
      replace: path=/etc/apache2/sites-available/000-default.conf regexp='DocumentRoot /var/www/html' replace='DocumentRoot /data/html' backup=yes
      when: true
      notify: restart apache
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
